title: "Model Context Protocol (MCP) Complete Guide"
description: "A comprehensive technical guide to understanding and implementing the Model Context Protocol"

markdown: kramdown
highlighter: rouge

# Build settings
exclude:
  - "*.docx"
  - "*.pdf"
  - "*.html"
  - ".claude/"
  - "~$*"